id: P009375
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD17630
  title: 'ཀུན་འདུས་མེ་ལོང་། སློབ་ཆུང་མཐར་ཕྱིན་སློབ་མའི་ཕྱོགས་བསྡུས་བསྐྱར་སྦྱོང་། '
  author: ''
  volumes:
    0401223924f640f19b7c7f8d03753069:
      image_group_id: I2PD19286
      title: ''
      volume_number: 1
      total_pages: 226
      base_file: v001.txt
